using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mapwright.Generator;

/// <summary>
/// The Mapwright incremental generator. Finds [Mapper] partial classes, plans every
/// unimplemented partial method into a mapping model (all semantic work happens there),
/// and emits the implementations as plain C#. Unchanged mapper syntax short-circuits on
/// the cached model, so large solutions pay for mapping generation only when a mapper or
/// its models actually change.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MapwrightGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mappers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Mapwright.MapperAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                    new MapPlanner((INamedTypeSymbol)ctx.TargetSymbol, ctx.SemanticModel.Compilation).Plan());

        context.RegisterSourceOutput(mappers, static (spc, model) =>
        {
            foreach (var diagnostic in model.Diagnostics)
            {
                spc.ReportDiagnostic(diagnostic.ToDiagnostic());
            }

            if (model.Methods.Length > 0)
            {
                spc.AddSource(model.HintName, SourceText.From(Emit(model), Encoding.UTF8));
            }
        });
    }

    private static string Emit(MapperClassModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by Mapwright — the mapping code below is yours to read, debug, and step through />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        if (model.Namespace is not null)
        {
            builder.AppendLine($"namespace {model.Namespace};");
            builder.AppendLine();
        }

        builder.AppendLine(model.ClassDeclaration);
        builder.AppendLine("{");

        var first = true;
        foreach (var method in model.Methods)
        {
            if (!first)
            {
                builder.AppendLine();
            }

            first = false;
            EmitMethod(builder, method);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitMethod(StringBuilder builder, MapMethodModel method)
    {
        switch (method.Kind)
        {
            case MapKind.Object:
                builder.AppendLine($"    {method.Signature}");
                builder.AppendLine("    {");
                if (!method.SourceIsValueType)
                {
                    builder.AppendLine($"        global::System.ArgumentNullException.ThrowIfNull({method.SourceParameterName});");
                }

                builder.AppendLine($"        var result = new {method.ConstructedTypeFq}");
                builder.AppendLine("        {");
                foreach (var assignment in method.Assignments)
                {
                    builder.AppendLine($"            {assignment},");
                }

                builder.AppendLine("        };");
                if (method.AfterMapName is not null)
                {
                    builder.AppendLine($"        {method.AfterMapName}({method.SourceParameterName}, result);");
                }

                builder.AppendLine("        return result;");
                builder.AppendLine("    }");
                break;

            case MapKind.Copy:
                builder.AppendLine($"    {method.Signature}");
                builder.AppendLine("    {");
                if (!method.SourceIsValueType)
                {
                    builder.AppendLine($"        global::System.ArgumentNullException.ThrowIfNull({method.SourceParameterName});");
                    builder.AppendLine($"        global::System.ArgumentNullException.ThrowIfNull({method.TargetParameterName});");
                }

                foreach (var statement in method.Assignments)
                {
                    builder.AppendLine($"        {method.TargetParameterName}.{statement}");
                }

                if (method.AfterMapName is not null)
                {
                    builder.AppendLine($"        {method.AfterMapName}({method.SourceParameterName}, {method.TargetParameterName});");
                }

                builder.AppendLine("    }");
                break;

            case MapKind.Projection:
                builder.AppendLine($"    {method.Signature} =>");
                builder.AppendLine($"        {method.SourceParameterName} => new {method.ConstructedTypeFq}");
                builder.AppendLine("        {");
                foreach (var assignment in method.Assignments)
                {
                    builder.AppendLine($"            {assignment},");
                }

                builder.AppendLine("        };");
                break;

            case MapKind.Collection:
                builder.AppendLine($"    {method.Signature}");
                builder.AppendLine("    {");
                builder.AppendLine($"        global::System.ArgumentNullException.ThrowIfNull({method.SourceParameterName});");
                builder.AppendLine($"        return {method.CollectionBody};");
                builder.AppendLine("    }");
                break;
        }
    }
}
